FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    streamlit==1.35.0 \
    folium==0.16.0 \
    streamlit-folium \
    pandas==2.2.2 \
    numpy==1.26.4 \
    requests \
    python-dotenv==1.0.1

COPY dashboard/app.py   ./dashboard/app.py
COPY dashboard/utils.py ./dashboard/utils.py

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", \
     "--server.port=8501", \
     "--server.address=0.0.0.0", \
     "--server.headless=true"]